//
//  TransactionDetailsScreenInteractor.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 25/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import CoreData

class TransactionDetailsScreenInteractor: TransactionDetailsScreenPresentorToInterectorProtocol {
    
    var presenter: TransactionDetailsScreenInterectorToPresenterProtocol?
    var date: String?
    var filterRecords = [Record]()
    
    func getData() {
        let fetchRequest: NSFetchRequest<Record> = Record.fetchRequest()
        
        do {
            let records = try PersistenceManager.context.fetch(fetchRequest)
            filterRecords = records.filter { $0.createdDate == date }
            print(filterRecords)
            presenter?.passData(records: filterRecords)
        } catch {}
    }
    
    func clickDelete(_ record: Record) {
        PersistenceManager.context.delete(record)
        PersistenceManager.save()
        getData()
        presenter?.deleteSuccess(records: filterRecords)
    }
}
