//
//  TransactionDetailsScreenPresenter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 25/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

class TransactionDetailsScreenPresenter: TransactionDetailsScreenViewToPresenterProtocol {
    
    var view: TransactionDetailsScreenPresenterToViewProtocl?
    var router: TransactionDetailsScreenPresenterToRouterProtocol?
    var interactor: TransactionDetailsScreenPresentorToInterectorProtocol?

    init(view: TransactionDetailsScreenPresenterToViewProtocl, interactor: TransactionDetailsScreenPresentorToInterectorProtocol, router: TransactionDetailsScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func started() {
        view?.initialControlSetup()
    }

    func getData() {
        interactor?.getData()
    }
    
    func clickRecord(_ record: Record) {
        view?.showAlertBox(record)
    }
    
    func clickDelete(_ record: Record) {
        interactor?.clickDelete(record)
    }
}

// MARK: - Interactor to Presenter
extension TransactionDetailsScreenPresenter: TransactionDetailsScreenInterectorToPresenterProtocol {
    func deleteSuccess(records: [Record]) {
        view?.deleteSuccess(records: records)
    }
    
    func passData(records: [Record]) {
        view?.passData(records: records)
    }
}

