//
//  TransactionDetailsScreenRouter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 25/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class TransactionDetailsScreenRouter {

    var viewController: UIViewController
    init(view: UIViewController) {
        self.viewController = view
    }

}

// MARK: - Presenter to Wireframe Interface
extension TransactionDetailsScreenRouter: TransactionDetailsScreenPresenterToRouterProtocol {

    func gotoNextScreen(fromVC: UIViewController) {
        if let vc = fromVC.storyboard?.instantiateViewController(withIdentifier: "" ) {
            fromVC.present(vc, animated: true)
        }
    }

}
