//
//  TransactionDetailsScreenModuleBuilder.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 25/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class TransactionDetailsScreenModuleBuilder {

    static func build(_ date: String) -> UIViewController {
        let storyboard = UIStoryboard.init(name: "TransactionDetailsScreen", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "TransactionDetailsScreenId") as! TransactionDetailsScreenView
        let interactor = TransactionDetailsScreenInteractor()
        let router = TransactionDetailsScreenRouter(view: view)
        let presenter = TransactionDetailsScreenPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        interactor.date = date
        return view
    }

}
