//
//  SelectCategoryScreenPresenter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

class SelectCategoryScreenPresenter: SelectCategoryScreenViewToPresenterProtocol {
    
    var view: SelectCategoryScreenPresenterToViewProtocl?
    var router: SelectCategoryScreenPresenterToRouterProtocol?
    var interactor: SelectCategoryScreenPresentorToInterectorProtocol?

    init(view: SelectCategoryScreenPresenterToViewProtocl, interactor: SelectCategoryScreenPresentorToInterectorProtocol, router: SelectCategoryScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func started() {
        view?.initialControlSetup()
    }
    
    func getData() {
        interactor?.getData()
    }
}

// MARK: - Interactor to Presenter
extension SelectCategoryScreenPresenter: SelectCategoryScreenInterectorToPresenterProtocol {
    func passData(categories: [String]) {
        view?.passData(categories: categories)
    }
}

