//
//  SelectCategoryScreenView.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//
import Foundation
import UIKit

class SelectCategoryScreenView: UIViewController {
    @IBOutlet weak var tableView: UITableView!
    
    var presenter: SelectCategoryScreenViewToPresenterProtocol?
    var delegate: SelectCategoryDelegate?
    var categories: [String] = [String]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }

    override func viewWillAppear(_ animated: Bool) {
        presenter?.getData()
    }
}

// MARK: - UISetup
extension SelectCategoryScreenView {
    private func setup() {
        defaultUI()
        tableViewSetup()
    }
    
    private func defaultUI() {
        self.navigationController?.navigationStyle()
        self.title = "Select Category"
        self.navigationItem.backButtonStyle()
        self.tableView.tableViewUIStyle()
    }
    
    private func tableViewSetup() {
        tableView.delegate = self
        tableView.dataSource = self
        registerCell()
    }
    
    private func registerCell() {
        let selectCategoryNib = UINib(nibName: NibName.selectCategoryNib, bundle: nil)
        tableView.register(selectCategoryNib, forCellReuseIdentifier: CellID.selectCategoryCell)
    }
}

// MARK: - Presenter to View
extension SelectCategoryScreenView: SelectCategoryScreenPresenterToViewProtocl {
    func passData(categories: [String]) {
        self.categories = categories
        tableView.reloadData()
    }

    func initialControlSetup() {
        setup()
    }
}

extension SelectCategoryScreenView: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return categories.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: CellID.selectCategoryCell, for: indexPath) as! SelectCategoryTableViewCell
        let category = categories[indexPath.row]
        cell.setData(categoryName: category)
        cell.selectionStyle = .none
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let category = categories[indexPath.row]
        delegate?.selectCategory(category)
        self.navigationController?.popViewController(animated: true)
    }
}
