//
//  SelectCategoryScreenInteractor.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation


class SelectCategoryScreenInteractor: SelectCategoryScreenPresentorToInterectorProtocol {
    
    var categories: [String] = ["Food", "Transport", "Shopping", "Entertainment", "Travel", "Bills", "Health"]
    
    var presenter: SelectCategoryScreenInterectorToPresenterProtocol?
    
    func getData() {
        presenter?.passData(categories: categories)
    }
}
