//
//  SelectCategoryScreenModuleBuilder.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class SelectCategoryScreenModuleBuilder {

    static func build(fromVC: UIViewController) -> UIViewController {
        let storyboard = UIStoryboard.init(name: "SelectCategoryScreen", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "SelectCategoryScreenId") as! SelectCategoryScreenView
        let interactor = SelectCategoryScreenInteractor()
        let router = SelectCategoryScreenRouter(view: view)
        let presenter = SelectCategoryScreenPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter
        view.delegate = fromVC as? SelectCategoryDelegate
        interactor.presenter = presenter
        return view
    }

}
