//
//  AddIncomeExpenseScreenInteractor.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation


class AddIncomeExpenseScreenInteractor: AddIncomeExpenseScreenPresentorToInterectorProtocol {
    
    var presenter: AddIncomeExpenseScreenInterectorToPresenterProtocol?
    
    func clickSaveButton(type: String, category: String, date: String, amount: String, note: String) {
        if validateValues(category: category, date: date, amount: amount, note: note) {
            printDebug("Success")
            let record = Record(context: PersistenceManager.context)
            record.type = type
            record.category = category
            record.createdDate = date
            record.amount = Double(amount)!
            record.note = note
            PersistenceManager.save()
            presenter?.addSuccess()
        }
    }
    
    private func validateValues(category: String, date: String, amount: String, note: String) -> Bool {
        var success: Bool  = true
        if category.isEmpty && date.isEmpty && amount.isEmpty && note.isEmpty {
            presenter?.allTextfieldsAreEmpty()
            success = false
        }
        if category.isEmpty {
            presenter?.categoryTextFieldIsEmpty()
            success = false
        }
        if date.isEmpty {
            presenter?.dateTextfieldIsEmpty()
            success = false
        }
        if amount.isEmpty {
            presenter?.amountTextfieldIsEmpty()
            success = false
        }
        if note.isEmpty {
            presenter?.noteTextfieldIsEmpty()
            success = false
        }
        return success
    }
}
