//
//  AddIncomeExpenseScreenRouter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 21/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class AddIncomeExpenseScreenRouter {

    var viewController: UIViewController
    init(view: UIViewController) {
        self.viewController = view
    }

}

// MARK: - Presenter to Wireframe Interface
extension AddIncomeExpenseScreenRouter: AddIncomeExpenseScreenPresenterToRouterProtocol {
    func gotoSelectCategoryScreen(fromVC: UIViewController) {
        let toVC = SelectCategoryScreenModuleBuilder.build(fromVC: fromVC)
        fromVC.navigationController?.pushViewController(toVC, animated: true)
    }
}
