//
//  TransactionScreenModuleBuilder.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class TransactionScreenModuleBuilder {

    static func build() -> UIViewController {
        let storyboard = UIStoryboard.init(name: "TransactionScreen", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "TransactionScreenId") as! TransactionScreenView
        let interactor = TransactionScreenInteractor()
        let router = TransactionScreenRouter(view: view)
        let presenter = TransactionScreenPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        return view
    }

}
