//
//  TransactionScreenInteractor.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import CoreData

class TransactionScreenInteractor: TransactionScreenPresentorToInterectorProtocol {
    
    var presenter: TransactionScreenInterectorToPresenterProtocol?
    var seen = Set<String>()
    var seen2 = Set<String>()
    var dateRecords = [Record]()
    
    func getData() {
        let fetchRequest: NSFetchRequest<Record> = Record.fetchRequest()
        fetchRequest.returnsObjectsAsFaults = false
        do {
                let records = try PersistenceManager.context.fetch(fetchRequest)
                for record in records {
                    if !seen.contains(record.createdDate) {
                        dateRecords.append(record)
                        seen.insert(record.createdDate)
                    }
                }
        } catch {}
        presenter?.passData(records: dateRecords)
        seen = []
        dateRecords = []
    }
}
