//
//  TransactionScreenProtocols.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

//Presenter -> View
protocol TransactionScreenPresenterToViewProtocl: class {
    func initialControlSetup()
    func passData(records: [Record])
}

//View -> Presenter
protocol TransactionScreenViewToPresenterProtocol: class {
    var view: TransactionScreenPresenterToViewProtocl? {get set}
    var interactor: TransactionScreenPresentorToInterectorProtocol? {get set}
    func started()
    func getData()
    func clickDate(_ date: String)
}

//Interactor -> Presenter
protocol TransactionScreenInterectorToPresenterProtocol: class {
    func passData(records: [Record])
}

//Presenter -> Interactor
protocol TransactionScreenPresentorToInterectorProtocol: class {
    var presenter: TransactionScreenInterectorToPresenterProtocol? {get set}
    func getData()
}

//Presenter -> Router or WireFrame
protocol TransactionScreenPresenterToRouterProtocol: class {
    func gotoNextScreen(fromVC: UIViewController, _ date: String)
}


