//
//  TransactionScreenRouter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class TransactionScreenRouter {

    var viewController: UIViewController
    init(view: UIViewController) {
        self.viewController = view
    }

}

// MARK: - Presenter to Wireframe Interface
extension TransactionScreenRouter: TransactionScreenPresenterToRouterProtocol {
    
    func gotoNextScreen(fromVC: UIViewController, _ date: String) {
        let showTransactionDetailVC = TransactionDetailsScreenModuleBuilder.build(date)
        fromVC.navigationController?.pushViewController(showTransactionDetailVC, animated: true)
    }
}
