//
//  TransactionScreenPresenter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

class TransactionScreenPresenter: TransactionScreenViewToPresenterProtocol {
    
    var view: TransactionScreenPresenterToViewProtocl?
    var router: TransactionScreenPresenterToRouterProtocol?
    var interactor: TransactionScreenPresentorToInterectorProtocol?

    init(view: TransactionScreenPresenterToViewProtocl, interactor: TransactionScreenPresentorToInterectorProtocol, router: TransactionScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func started() {
        view?.initialControlSetup()
    }

    func getData() {
        interactor?.getData()
    }
    
    func clickDate(_ date: String) {
        if let fromVC = self.view as? UIViewController {
            self.router?.gotoNextScreen(fromVC: fromVC, date)
        }
    }
}

// MARK: - Interactor to Presenter
extension TransactionScreenPresenter: TransactionScreenInterectorToPresenterProtocol {
    func passData(records: [Record]) {
        view?.passData(records: records)
    }
}

