//
//  TransactionScreenView.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 23/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//
import Foundation
import UIKit

class TransactionScreenView: UIViewController {
    
    @IBOutlet weak var searchBar: UISearchBar!
    @IBOutlet weak var tableView: UITableView!
    
    var transactionRecords = [Record]()
    var searchdata = [Record]()
    var presenter: TransactionScreenViewToPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        presenter?.getData()
    }
}

// MARK: - UISetup
extension TransactionScreenView {
    private func setup() {
        defaultUI()
        searchBarSetup()
        tableViewSetup()
    }
    
    private func defaultUI() {
        self.navigationController?.navigationStyle()
        self.title = "Transactions"
        self.navigationItem.backButtonStyle()
        self.tableView.tableViewUIStyle()
    }
    
    private func searchBarSetup() {
        searchBar.backgroundColor = .white
        searchBar.delegate = self
    }
    
    private func tableViewSetup() {
        tableView.delegate = self
        tableView.dataSource = self
        registerCell()
    }
    
    private func registerCell() {
        let transactionNib = UINib(nibName: NibName.transactionNib, bundle: nil)
        tableView.register(transactionNib, forCellReuseIdentifier: CellID.transactionCell)
    }
}

// MARK: - Presenter to View
extension TransactionScreenView: TransactionScreenPresenterToViewProtocl {
    func passData(records: [Record]) {
        transactionRecords = records
        searchdata = transactionRecords
        tableView.reloadData()
    }
    
    func initialControlSetup() {
        setup()
    }

}

extension TransactionScreenView: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return searchdata.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: CellID.transactionCell, for: indexPath) as! TransactionsTableViewCell
        let date = searchdata[indexPath.row].createdDate 
        cell.setData(createdDate: date)
        cell.selectionStyle = .none
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let date = searchdata[indexPath.row].createdDate
        presenter?.clickDate(date)
    }
}

extension TransactionScreenView: UISearchBarDelegate {
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        searchdata = transactionRecords.filter { (($0 as Record).createdDate).range(of: searchBar.text ?? "", options: [ .caseInsensitive, .diacriticInsensitive ]) != nil }
        if searchText.isEmpty {
            searchdata = transactionRecords
        }
        tableView.reloadData()
    }
}
