//
//  HomeScreenInteractor.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 20/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import CoreData

class HomeScreenInteractor: HomeScreenPresentorToInterectorProtocol {
    
    var presenter: HomeScreenInterectorToPresenterProtocol?
    var incomeRecords = [Record]()
    var expenseRecords = [Record]()
    
    func getData(_ date: String) {
        var income: Double = 0.0
        var expense: Double = 0.0
        var savings: Double = 0.0
        let fetchRequest: NSFetchRequest<Record> = Record.fetchRequest()
        
        do {
            let records = try PersistenceManager.context.fetch(fetchRequest)
            incomeRecords = records.filter { $0.createdDate == date && $0.type == "Income" }
            expenseRecords = records.filter { $0.createdDate == date && $0.type == "Expense" }
            for record in incomeRecords {
                income += record.amount
            }
            print("Incomes >>>>" , income)
            for record in expenseRecords {
                expense += record.amount
            }
            print("Expense >>>" , expense)
            savings = income - expense
            presenter?.passData(income, expense, savings: savings)
        } catch {}
    }
}
