//
//  HomeScreenModuleBuilder.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 20/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class HomeScreenModuleBuilder {

    static func build() -> UIViewController {
        let storyboard = UIStoryboard.init(name: "HomeScreen", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "HomeScreenId") as! HomeScreenView
        let interactor = HomeScreenInteractor()
        let router = HomeScreenRouter(view: view)
        let presenter = HomeScreenPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        return view
    }

}
