//
//  HomeScreenPresenter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 20/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

class HomeScreenPresenter: HomeScreenViewToPresenterProtocol {
    
    var view: HomeScreenPresenterToViewProtocl?
    var router: HomeScreenPresenterToRouterProtocol?
    var interactor: HomeScreenPresentorToInterectorProtocol?

    init(view: HomeScreenPresenterToViewProtocl, interactor: HomeScreenPresentorToInterectorProtocol, router: HomeScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func started() {
        view?.initialControlSetup()
    }

    func clickDateButton() {
        view?.showDatePicker()
    }
    
    func clickViews(screenName: String) {
        if let fromVC = self.view as? UIViewController {
            self.router?.checkAndPushScreen(fromVC: fromVC, screenName: screenName)
        }
    }
    
    func getData(_ date: String) {
        interactor?.getData(date)
    }
}

// MARK: - Interactor to Presenter
extension HomeScreenPresenter: HomeScreenInterectorToPresenterProtocol {
    func passData(_ income: Double, _ expense: Double, savings: Double) {
        view?.passData(income, expense, savings: savings)
    }
}

