//
//  HomeScreenEntity.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 20/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
