//
//  SplashScreenRouter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 28/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class SplashScreenRouter {

    var viewController: UIViewController
    init(view: UIViewController) {
        self.viewController = view
    }

}

// MARK: - Presenter to Wireframe Interface
extension SplashScreenRouter: SplashScreenPresenterToRouterProtocol {

    func gotoNextScreen(fromVC: UIViewController) {
        let toVC = HomeScreenModuleBuilder.build()
        let nav = UINavigationController.init(rootViewController: toVC)
        nav.modalPresentationStyle = .fullScreen
        nav.modalTransitionStyle = .crossDissolve
        fromVC.present(nav, animated: true)
    }

}
