//
//  SplashScreenPresenter.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 28/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import Foundation
import UIKit

class SplashScreenPresenter: SplashScreenViewToPresenterProtocol {
    
    var view: SplashScreenPresenterToViewProtocl?
    var router: SplashScreenPresenterToRouterProtocol?
    var interactor: SplashScreenPresentorToInterectorProtocol?

    init(view: SplashScreenPresenterToViewProtocl, interactor: SplashScreenPresentorToInterectorProtocol, router: SplashScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func started() {
        view?.initialControlSetup()
    }
    
    func gotoNextScreen() {
        if let fromVC = self.view as? UIViewController {
            self.router?.gotoNextScreen(fromVC: fromVC)
        }
    }

}

// MARK: - Interactor to Presenter
extension SplashScreenPresenter: SplashScreenInterectorToPresenterProtocol {

}

