//
//  SplashScreenView.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 28/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//
import Foundation
import UIKit

class SplashScreenView: UIViewController {

    var presenter: SplashScreenViewToPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }

    private func gotoHomeScreen() {
        Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { (timer) in
            self.presenter?.gotoNextScreen()
        }
    }

}

// MARK: - Presenter to View
extension SplashScreenView: SplashScreenPresenterToViewProtocl {

    func initialControlSetup() {
        gotoHomeScreen()
    }
}
