//
//  SplashScreenModuleBuilder.swift
//  MoneyManager
//
//  Created Tin Tun Aung on 28/01/2020.
//  Copyright © 2020 Tin Tun Aung. All rights reserved.
//
//  Template generated by Tin Tun Aung
//

import UIKit
import Foundation

class SplashScreenModuleBuilder {

    static func build() -> UIViewController {
        let storyboard = UIStoryboard.init(name: "SplashScreen", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "SplashScreenId") as! SplashScreenView
        let interactor = SplashScreenInteractor()
        let router = SplashScreenRouter(view: view)
        let presenter = SplashScreenPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        return view
    }

}
